web:
  build: .
  ports:
    - "80:8080"
    - "3030:3030"
  links:
    - db:db
db:
  image: postgres:9.4.4
  volumes:
    - ./db/dumps:/app-db-dumps # We're mounting this folder so we can backup/restore database dumps from our app folder.
  environment:
    LC_ALL: C.UTF-8
    POSTGRES_PASSWORD: docker
    POSTGRES_USER: docker
