version: '2'
services:
  web:
    build: .
    ports:
      - "80:8080"
      - "3030:3030"
    links:
      - db:db
  db:
    image: postgres:9.4.4
    volumes:
      - dbdata:/var/lib/postgres/data
      - dblogs:/var/log/postgresql
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker

volumes:
  dbdata:
    driver: local
  dblogs:
    driver: local
